name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout configs
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: rhiadciccoli/ms-base-go:${{ github.sha }}
      - 
        name: Checkout configs
        uses: actions/checkout@v3
        with:
          repository: Rhiadc/infra-ms-base
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: .
          ref: main

      -
        name: Install yq
        run: |
          VERSION=v4.2.0 
          BINARY=yq_linux_amd64
          wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq &&\
          chmod +x /usr/bin/yq

          yq --version
