name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout configs
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: rhiadciccoli/ms-base-go:${{ github.sha }}
      - 
        name: Checkout configs
        uses: actions/checkout@v3
        with:
          repository: Rhiadc/infra-ms-base
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: .
          ref: main

      - 
        name: Bump image tag
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag = strenv(GITHUB_SHA)' values.prod.yaml

          
      - 
        name: config git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      
      - 
        name: add file
        run : |
          git checkout -b chore/bump-docker-version
          git add .
          git commit -m "bump docker version"
          git push -u origin chore/bump-docker-version
